"""update contact fields

Revision ID: 46501db38e0d
Revises: a202a6550139
Create Date: 2025-10-06 15:46:21.830157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46501db38e0d'
down_revision = 'a202a6550139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('division', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('coach_full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('coach_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('manager_full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('manager_email', sa.String(length=120), nullable=True))
        batch_op.drop_column('contact_name')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('manager_email')
        batch_op.drop_column('manager_full_name')
        batch_op.drop_column('coach_email')
        batch_op.drop_column('coach_full_name')
        batch_op.drop_column('division')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
