"""Add Team and PracticePlan models for practice plans system

Revision ID: 688824474a73
Revises: 56ad8e1a459c
Create Date: 2025-09-02 16:45:37.946144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688824474a73'
down_revision = '56ad8e1a459c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('season',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('season',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
