"""add extra_teams to player

Revision ID: a202a6550139
Revises: ad8735c527fb
Create Date: 2025-10-04 11:20:23.191791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a202a6550139'
down_revision = 'ad8735c527fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_teams', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('extra_teams')

    # ### end Alembic commands ###
